# Generated by Django 3.1.7 on 2021-04-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='main_image',
        ),
    ]
