# Generated by Django 3.1.7 on 2021-04-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210420_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='intro',
            field=models.TextField(),
        ),
    ]
