# Generated by Django 3.1.7 on 2021-04-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogpost_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposttag',
            old_name='BlogPost',
            new_name='blogpost',
        ),
    ]
