# Generated by Django 3.1.7 on 2021-04-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210419_0915'),
        ('profiles', '0001_initial'),
        ('blog', '0011_auto_20210421_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposttag',
            name='blogpost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taggedblogposts', to='blog.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogposttag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogposttags', to='products.tag'),
        ),
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('blogpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogpostcomments', to='blog.blogpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usersblogpostcomments', to='profiles.userprofile')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
