# Generated by Django 3.1.7 on 2021-04-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210422_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostcomment',
            name='title',
        ),
    ]
