# Generated by Django 3.1.7 on 2021-03-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_county',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_postcode',
            new_name='postcode',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_street_address1',
            new_name='street_address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_street_address2',
            new_name='street_address2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='billing_town_or_city',
            new_name='town_or_city',
        ),
    ]
