# Generated by Django 3.1.7 on 2021-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210331_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='original_cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_county',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_street_address1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_street_address2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_town_or_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_pid',
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=40),
        ),
    ]
