# Generated by Django 3.1.7 on 2021-04-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_auto_20210427_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_price_paid',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
    ]
