# Generated by Django 3.1.7 on 2021-04-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='discount_amount',
            new_name='percentage_discount',
        ),
    ]
