# Generated by Django 3.1.7 on 2021-04-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210429_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='code',
            new_name='discount_code',
        ),
    ]
