# Generated by Django 3.1.7 on 2021-03-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('image1_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='product_images')),
                ('image2_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='products.image'),
        ),
    ]
