# Generated by Django 3.1.7 on 2021-03-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210318_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_information',
            new_name='information',
        ),
    ]
